; Generated by parena build (LLVM target) -- VS0-for-LLVM v0, do not edit by hand.

declare void @reflux_host_dispatch(i32, i32, i32, i32)
declare i32 @reflux_host_log_size()
declare i32 @reflux_host_action_type_at(i32)
declare i32 @reflux_host_action_a_at(i32)
declare i32 @reflux_host_action_b_at(i32)
declare i32 @reflux_host_action_c_at(i32)

define void @reflux_dispatch(i32 %action_type, i32 %a, i32 %b, i32 %c) {
entry:
  call void @reflux_host_dispatch(i32 %action_type, i32 %a, i32 %b, i32 %c)
  ret void
}

define i32 @reflux_log_size() {
entry:
  %result = call i32 @reflux_host_log_size()
  ret i32 %result
}

define i32 @reflux_action_type_at(i32 %index) {
entry:
  %result = call i32 @reflux_host_action_type_at(i32 %index)
  ret i32 %result
}

define i32 @reflux_action_a_at(i32 %index) {
entry:
  %result = call i32 @reflux_host_action_a_at(i32 %index)
  ret i32 %result
}

define i32 @reflux_action_b_at(i32 %index) {
entry:
  %result = call i32 @reflux_host_action_b_at(i32 %index)
  ret i32 %result
}

define i32 @reflux_action_c_at(i32 %index) {
entry:
  %result = call i32 @reflux_host_action_c_at(i32 %index)
  ret i32 %result
}

