; Generated by parena build (LLVM target) -- VS0-for-LLVM v0, do not edit by hand.

declare i32 @tcp_listen_impl(i32)
declare i32 @tcp_accept_impl(i32)
declare i32 @tcp_close_impl(i32)

define i32 @tcp_listen_raw(i32 %port) {
entry:
  %result = call i32 @tcp_listen_impl(i32 %port)
  ret i32 %result
}

define i32 @tcp_accept_raw(i32 %listener_fd) {
entry:
  %result = call i32 @tcp_accept_impl(i32 %listener_fd)
  ret i32 %result
}

define i32 @tcp_close_raw(i32 %fd) {
entry:
  %result = call i32 @tcp_close_impl(i32 %fd)
  ret i32 %result
}

